--- 
pid: tmp/pids/thin.pid
socket: /tmp/thin.sock
wait: 30
log: log/thin.log
timeout: 30
max_conns: 1024
chdir: /Users/MacBury/Sites/Rails/cart-on-rails
environment: development
max_persistent_conns: 512
servers: 1
require: []

